spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autic
    username: postgres
    password: 123
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: update
hibernate:
  show_sql: true
log4j.logger.org.hibernate.SQL: DEBUG
log4j.logger.org.hibernate.type: TRACE
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080
org:
  springframework:
    boot:spring-boot-starter-thymeleaf
