spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoc
    username: postgres
    password: 123
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: update
hibernate:
  show_sql: true
log4j.logger.org.hibernate.SQL: DEBUG
log4j.logger.org.hibernate.type: TRACE